[env:teensy41]
platform      = teensy
board         = teensy41
framework     = arduino
monitor_speed = 2000000
lib_ignore    = ArduinoStub
build_flags =
    -O2
    -mfpu=fpv5-sp-d16
    -mfloat-abi=hard
    -std=gnu++14
    -Wall
    -Wextra
    -Wdouble-promotion

[env:native]
platform = native
build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -Wdouble-promotion
    -Wno-unused-function
    -Wno-unused-variable
    -I lib/ArduinoStub
    -DNATIVE_MAIN

[env:native_test]
platform       = native
test_framework = unity
build_flags =
    -std=gnu++17
    -Wall
    -Wno-unused-function
    -Wno-unused-variable
    -I lib/ArduinoStub
    -DNATIVE_MAIN
